version: '3'
# task install-mkdocs
# task serve-mkdocs
# task publish-mkdocs
# task release

tasks:
  # Generate the documentation
  # We use [mkdocs](https://www.mkdocs.org/)
  install-mkdocs:
    cmds:
      - pipx install mkdocs-material --include-deps
  serve-mkdocs:
    cmds:
      - mkdocs serve
  publish-mkdocs: # on the `main` branch
    cmds:
      - mkdocs gh-deploy

  # Generate a release of the capsule MDK
  release:
    env:
      #TAG: "v0.0.1"
      #TAG: "v0.0.2" 
      #TAG: "v0.0.3" 
      #TAG: "v0.0.4"
      #TAG: "v0.0.5"
      #TAG: "v0.0.6"
      TAG: "v0.0.7"
    cmds:
      - echo "📦 Generating release..."
      - git add .
      - git commit -m "📦 updates HDK for ${TAG}"
      - git tag ${TAG}
      - git push origin main ${TAG}

  remove-tag:
    env:
      TAG: "v0.0.7"
    cmds:
      - git tag -d ${TAG}
